### ISSUE TITLE
empty repository

### ISSUE THREAD

**Issue by joeychsu** [NickRuiz/power-asr#1]
After reviewing your paper [Phonetically-oriented word error alignment for speech recognition error analysis in speech translation],
I think it would be very useful in my work.
Would you update this repository recently?

**Comment by ucaslyc** [comment]
I think POWER alignment is very interesting and would be helpful for my work. 
Did you get the code?  @joeychsu 
Or Could you please update this repository? @NickRuiz

**Comment by joeychsu** [comment]
@ucaslyc no

**Comment by NickRuiz** [comment]
Apologies for never getting around to making this public. I'm working on a slow roll-out now, starting with the basic word alignment algorithm and will roll in the phoneme back-off alignment soon. It'll take a bit of effort to get Festival running again.

**Comment by NickRuiz** [comment]
Ok guys! You should be able to run power.py to evaluate and score/align outputs.
